### ISSUE TITLE
Failed RTM connect (1.3.2)

### ISSUE THREAD

**Issue by 4923** [4923/slackbot_playground#1]
- [x] Changed to `slackclient==1.3.2` 

Following tutorial: https://www.fullstackpython.com/blog/build-first-slack-bot-python.html and RTM connect issue occured

$ python main.py
Failed RTM connect
Traceback (most recent call last):
  File "C:\Users\lky\Desktop\Repo\slackbot_playground\yeongja_bot\yeongja_bot_venv\lib\site-packages\slackclient\client.py", line 140, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "C:\Users\lky\Desktop\Repo\slackbot_playground\yeongja_bot\yeongja_bot_venv\lib\site-packages\slackclient\server.py", line 168, in rtm_connect
    raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
Connection failed. Exception traceback printed above.
(yeongja_bot_venv) (base)

### checked list
- [x] Token : starts with **`xoxb`: Bot User OAuth Access Token**, not `xoxp`: OAuth Access Token
- [x] `python2 main.py`
- [x] Read up **[slackapi wiki](https://github.com/slackapi/python-slack-sdk/wiki/Migrating-to-2.x)**

**Comment by 4923** [comment]
first of all : fix the module name `slackclient` into `slack`
- `ImportError: No module named slackclient` issue showed up: Pylance couldn't resolve slackclient
- According to the below issue, `slackclient` package only used when user install it. After that, `import slack` would be correct.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/60145951/157194211-47337bce-a1ea-4dfd-9b0c-8e5c33b947b9.png">

**Comment by 4923** [comment]
- New OS: Window -> Mac
In MacOS, default version of python is 2.xx, so every command should clarify the version is 3. (e.g. `python3 ~` `pip3 ~`)
- Change Workspace Name, Renew App API list

The issue doesn't reproduce now, therefore close.
