### ISSUE TITLE
The server responded with: {'ok': False, 'error': 'not_in_channel'}

### ISSUE THREAD

**Issue by 4923** [4923/slackbot_playground#2]
### reproduce
```
$ cd yeongja_bot
$ source yeongja_bot_venv/Scripts/activate 
$ python3 basic.py
```

### error log
```
❯ python3 test.py
/opt/homebrew/lib/python3.9/site-packages/slack/deprecation.py:16: UserWarning: slack package is deprecated. Please use slack_sdk.web/webhook/rtm package instead. For more info, go to https://slack.dev/python-slack-sdk/v3-migration/
  warnings.warn(message)
Traceback (most recent call last):
  File "/Users/a4923/Desktop/repositories/clone_slackbot_playground/yeongja_bot/test.py", line 67, in <module>
    message_ts = slack.get_message_ts(channel_id, query)
  File "/Users/a4923/Desktop/repositories/clone_slackbot_playground/yeongja_bot/test.py", line 34, in get_message_ts
    result = self.client.conversations_history(channel=channel_id)
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_client.py", line 2356, in conversations_history
    return self.api_call("conversations.history", http_verb="GET", params=kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_base_client.py", line 167, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_base_client.py", line 258, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_base_client.py", line 389, in _urllib_api_call
    return SlackResponse(
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_slack_response.py", line 222, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'not_in_channel'}
```

### code
```py
def get_message_ts(self, channel_id, query):
        """
        슬랙 채널 내 메세지 조회
        """
        # conversations_history() 메서드 호출
        # TODO: The server responded with: {'ok': False, 'error': 'not_in_channel'}
        result = self.client.conversations_history(channel=channel_id)
        print(result)
        # 채널 내 메세지 정보 딕셔너리 리스트
        messages = result.data['messages']
        # 채널 내 메세지가 query와 일치하는 메세지 딕셔너리 쿼리
        message = list(filter(lambda m: m["text"]==query, messages))[0]
        # 해당 메세지ts 파싱
        message_ts = message["ts"]
        return message_ts
```

### TODO
- [x] Does chennel name or ID load succesfully?
- [x] `get_message_ts`: Check channel API description

**Comment by 4923** [comment]
`get_channel_id` function works.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/60145951/157201653-4e5f5ebd-b328-4aa9-9e7c-fea83cc61f8e.png">

- contents of variable: 'channels' printed successfully
- the number of channels is 3

**Comment by 4923** [comment]
### current Scopes

<img width="679" alt="image" src="https://user-images.githubusercontent.com/60145951/157202207-3cb083d7-1b08-4b8c-8ae6-d834417fb345.png">


- followed: https://wooiljeong.github.io/python/slack-bot/

**Comment by 4923** [comment]
Some API names changed.

`conversations` method that control user conversation were originally separated such as `conversations_list`, `conversations_history`, However, 2022-03-08 Web API represent the same API grouped by `conversations` method.  
(e.g. conversation_history -> conversations.history, conversation_list -> conversations.list)

- [conversations.list](https://api.slack.com/methods/conversations.list) Lists all channels in a Slack team.
- [conversations.history](https://api.slack.com/methods/conversations.history) Fetches a conversation's history of messages and events.

At this point, I need to
1. Modify Web API related to conversations
2. Add Bot OAuth Scope and reinstall, surely change SlackAPI(`token`) starts with `xoxb-

**Comment by 4923** [comment]
follow stackoverflow below
### [Slack api conversations.history returns error: not_in_channel](https://stackoverflow.com/questions/60198159/slack-api-conversations-history-returns-error-not-in-channel)

current: Somehow customized app wasn't added channel
presume: Judging from *account_inactive* error message, this issue might caused from authority between App and Channel/Workspace. 
action: Add `chat:write.public` Scope, regenerate change app token and change it

### Result (⬇️ )
<img width="663" alt="image" src="https://user-images.githubusercontent.com/60145951/157278465-c2b27ef5-4448-47a9-8838-55d4c6e16695.png">

**Comment by 4923** [comment]
### The server responded with: {'ok': False, 'error': 'account_inactive'}
```
❯ python3 basic.py
/opt/homebrew/lib/python3.9/site-packages/slack/deprecation.py:16: UserWarning: slack package is deprecated. Please use slack_sdk.web/webhook/rtm package instead. For more info, go to https://slack.dev/python-slack-sdk/v3-migration/
  warnings.warn(message)
Traceback (most recent call last):
  File "/Users/a4923/Desktop/repositories/clone_slackbot_playground/yeongja_bot/basic.py", line 76, in <module>
    channel_id = slack.get_channel_id(channel_name)
  File "/Users/a4923/Desktop/repositories/clone_slackbot_playground/yeongja_bot/basic.py", line 29, in get_channel_id
    result = self.client.conversations_list()
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_client.py", line 2483, in conversations_list
    return self.api_call("conversations.list", http_verb="GET", params=kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_base_client.py", line 167, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_base_client.py", line 258, in _sync_send
    return self._urllib_api_call(
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_base_client.py", line 389, in _urllib_api_call
    return SlackResponse(
  File "/opt/homebrew/lib/python3.9/site-packages/slack_sdk/web/legacy_slack_response.py", line 222, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'account_inactive'}
```
